# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = 1
b = 2

fib = [1,2]
even = [2]
n = 2
while n < 4_000_000
  n = fib[-1] + fib[-2]
  fib << n 
  even << n if n % 2 == 0
end

puts even.inject(:+)